[package]
name = "rust-docker-demo"
version = "0.1.0"
edition = "2021"
authors = ["Hasan Hakkaev ,hasan.hakkaev@gmx.at"] 
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
